In [1]:
import numpy as np

In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [3]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [4]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [5]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
a = np.array([[1, 2], [3, 4]])
print(a.ndim)
print(a.shape)
print(a.size)

2
(2, 2)
4


In [8]:
np.array([1, 2, 3]) + np.array([4, 5, 6])

array([5, 7, 9])

In [9]:
np.sum([[1, 2, 3], [4, 5, 6]], axis=0)

array([5, 7, 9])

In [10]:
np.where(np.array([10, 20, 30, 40]) > 25, np.array([10, 20, 30, 40]), 0)

array([ 0,  0, 30, 40])

In [11]:
np.dot([[1, 2], [3, 4]], [[5, 6], [7, 8]])

array([[19, 22],
       [43, 50]])